### ISSUE TITLE
no error message given when connection over ssl failed

### ISSUE THREAD

**Issue by flip111** [phergie/phergie-irc-bot-react#40] opened 2015-11-30 13:13 UTC
i had

```php
      'options' => [
        'transport' => 'ssl'
      ]
```

set, but without giving the port

```php
'serverport' => 6697,
```

The bot couldn't  connect, but no error message was given

**Comment by svpernova09** [comment] 2015-11-30 13:51
If this is still an issue, please update with some more debugging. 

I would expect the issue is on the specific Freenode server, or the network itself recovering from massvie DDoS yesterday.

If you've resolved this please close the issue.

**Comment by flip111** [comment] 2015-11-30 14:02
Well right now i can't debug this issue because the bot can not connect to the server because of DDoS issues. But this issue doesn't seem to be related to that (tested before today by 2 persons)

**Comment by svpernova09** [comment] 2015-12-03 03:48
Closing this as I've also confirmed it's not an issue with Pherige, it's an issue with SecureConnector from reactphp's socket-client: https://github.com/reactphp/socket-client/issues/55 As you've reported to them already.

**Closed by svpernova09** 2015-12-03 03:48 UTC

**Comment by flip111** [comment] 2015-12-03 07:39
The issue i filed on reactphp/socket-client describes a problem where it keeps trying to make a connection and so the process (php) is stuck. This issue is about phergie terminating without any error message. I don't get how you think they are the same issue???

**Comment by svpernova09** [comment] 2015-12-03 13:32
@flip111 if the process gets stuck in the socket-client how is Phergie supposed to know something went wrong? I'm not understanding how you expect Phergie to throw an error when it's waiting on a connection to be made that never is.

**Comment by flip111** [comment] 2015-12-03 15:01
eh i'm saying that in _this_ issue it's _not_ waiting for a connection instead it terminates early ...
